---
- hosts: all
  become: yes
  vars:
    http_port: 80
    max_clients: 200
    #remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    package:
      name: apache2
      state: absent
      update_cache: yes
