---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
      - name: install
        yum:
          name: install packages
          state: latest
          update_cache: true
        notify: ['start apache']
        with_items: ['apache2', 'nginx' ]
  handlers:
    - name: start apache
      service:
        name: apache2
        state: started

