- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: check for valid OS --> {{ansible_os_family}}
      fail:
        msg: This playbook accepts only Debian OS
      when: '{{ansible_os_family != "Debian" and ansible_os_family != "RedHat"}}'
    - name: Load package name from variable file
      include_vars:
        file: "{{ansible_os_family}}.yml"
    - name: install deb
      package:
        name: "{{item}}"
        state: present
        update_cache: true
      when: "{{ansible_os_family == 'Debian'}}"
      loop: ['apache2','php','libapache2-mod-php','php-mysql', 'phpmyadmin']

    - name: install redhat
      package:
        name: "{{item}}"
        state: present
        update_cache: true
      when: "{{ansible_os_family == 'RedHat'}}"
      loop: ['httpd','php','php-mysql']

    - name: copy index file
      template:
        src: index.php
        dest: /var/www/html
      notify: ['start and enable apache']
  handlers:
    - name: start and enable apache
      service:
        name: "{{service_name}}"
        state: started
        enabled: yes

